export const GET_GITHUB_REPOSITORIES = "GET_GITHUB_REPOSITORIES";
export const GET_GITHUB_REPOSITORIES_SUCCESS = "GET_GITHUB_REPOSITORIES_SUCCESS";
export const GET_GITHUB_REPOSITORIES_ERROR = "GET_GITHUB_REPOSITORIES_ERROR";